#!/usr/bin/env python

import pyVmomi
import argparse
import atexit
import itertools
from pyVmomi import vim, vmodl
from pyVim.connect import SmartConnect, Disconnect
import humanize
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

MBFACTOR = float(1 << 20)

printVM = False
printDatastore = True
printHost = True

Records = {}